name: JAR-Datei bauen
on:
  push:
    branches: [ "master" ]

jobs:
  job-lib-bauen:
    runs-on: ubuntu-latest
    steps:
    - name: Git-Repo auschecken
      uses: actions/checkout@v4
    - name: JDK einrichten
      uses: actions/setup-java@v4
      with:
        java-version: 23
        distribution: 'temurin'
        cache: maven
    - name: Maven-Installation checken
      run: chmod u+x mvnw && ./mvnw --version
    - name: Bibliotheken mit Maven bauen
      run: ./mvnw --batch-mode clean package
    - name: Jar-Datei mit Klassen veröffentlichen
      uses: actions/upload-artifact@v4
      with:
        name: BruchrechnerBibliothek-Binary
        path: target/bruchrechnen-*-SNAPSHOT.zip
        if-no-files-found: error
        retention-days: 3
    - name: Jar-Datei mit Quellcode veröffentlichen
      uses: actions/upload-artifact@v4
      with:
        name: BruchrechnerBibliothek-Quellcode
        path: target/bruchrechnen-*-SNAPSHOT-sources.zip
        if-no-files-found: error
        retention-days: 3
