name: JAR-Datei bauen
on:
  push:
    branches: [ "master" ]

jobs:
  job-lib-bauen:
    runs-on: ubuntu-latest
    steps:
    - name: Git-Repo auschecken
      uses: actions/checkout@v4
    - name: JDK einrichten
      uses: actions/setup-java@v4
      with:
        java-version: 23
        distribution: 'temurin'
        cache: maven
    - name: Maven-Installation checken
      run: chmod u+x mvnw && ./mvnw --version
    - name: Bibliotheken mit Maven bauen
      run: ./mvnw --batch-mode clean package
    - name: Source-Dateien hinzufügen
      run: zip -r target/bruchrechnen-0.0.1-SNAPSHOT-with-sources.zip target/bruchrechnen-*-SNAPSHOT.jar src/
    - name: Jar-Datei veröffentlichen
      uses: actions/upload-artifact@v4
      with:
        name: BruchrechnerBibliothek
        path: target/bruchrechnen-0.0.1-SNAPSHOT-with-sources.zip
        if-no-files-found: error
        retention-days: 3
